<?php
/**
 * AccountingTransactionModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * AccountingTransactionModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountingTransactionModelAttributes
{
    public string $strId = 'id';
    public string $strAccountCode = 'account_code';
    public string $strAmount = 'amount';
    public string $strBankTransferId = 'bank_transfer_id';
    public string $strCorrectionOfVoucherNo = 'correction_of_voucher_no';
    public string $strCreatedDate = 'created_date';
    public string $strCreatedFromImportJournalId = 'created_from_import_journal_id';
    public string $strCurrencyAmount = 'currency_amount';
    public string $strCurrencyCode = 'currency_code';
    public string $strCustomerAccountNo = 'customer_account_no';
    public string $strCustomMatchingReference = 'custom_matching_reference';
    public string $strDate = 'date';
    public string $strDepartmentCode = 'department_code';
    public string $strDescription = 'description';
    public string $strDim1Code = 'dim1_code';
    public string $strDim2Code = 'dim2_code';
    public string $strDim3Code = 'dim3_code';
    public string $strDocumentNo = 'document_no';
    public string $strEmployeeAccountNo = 'employee_account_no';
    public string $strExternalImportReference = 'external_import_reference';
    public string $strHasVoucherDocumentation = 'has_voucher_documentation';
    public string $strImportedVoucherNo = 'imported_voucher_no';
    public string $strIsCreatedFromEhf = 'is_created_from_ehf';
    public string $strIsNoteMainEntry = 'is_note_main_entry';
    public string $strIsReversed = 'is_reversed';
    public string $strLastChanged = 'last_changed';
    public string $strLocationCode = 'location_code';
    public string $strOurReferenceEmployeeCode = 'our_reference_employee_code';
    public string $strProductCode = 'product_code';
    public string $strProjectCode = 'project_code';
    public string $strQuantity = 'quantity';
    public string $strReversedVoucherNo = 'reversed_voucher_no';
    public string $strSubLedgerEntryId = 'sub_ledger_entry_id';
    public string $strSupplierAccountNo = 'supplier_account_no';
    public string $strText = 'text';
    public string $strVatAmount = 'vat_amount';
    public string $strVatCode = 'vat_code';
    public string $strVatRate = 'vat_rate';
    public string $strVatReturnSpecification = 'vat_return_specification';
    public string $strVoucherCid = 'voucher_cid';
    public string $strVoucherCreditNoteReference = 'voucher_credit_note_reference';
    public string $strVoucherDate = 'voucher_date';
    public string $strVoucherDueDate = 'voucher_due_date';
    public string $strVoucherId = 'voucher_id';
    public string $strVoucherImagesCount = 'voucher_images_count';
    public string $strVoucherNo = 'voucher_no';
    public string $strVoucherReference = 'voucher_reference';
    public string $strVoucherType = 'voucher_type';
}

