<?php
/**
 * BankJournalVoucherLineModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * BankJournalVoucherLineModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BankJournalVoucherLineModelFields
{
    public string $strId = 'id';
    public string $strAccountCode = 'accountCode';
    public string $strAmount = 'amount';
    public string $strCurrencyCode = 'currencyCode';
    public string $strCurrencyRate = 'currencyRate';
    public string $strDate = 'date';
    public string $strDescription = 'description';
    public string $strInvoiceNo = 'invoiceNo';
    public string $strVatCode = 'vatCode';
}

