<?php
/**
 * ClientModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * ClientModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientModelAttributes
{
    public string $strId = 'id';
    public string $strName = 'name';
    public string $strLegalName = 'legal_name';
    public string $strVatNumber = 'vat_number';
    public string $strMailAddress = 'mail_address';
    public string $strStreetAddress = 'street_address';
    public string $strEmailAddress = 'email_address';
    public string $strPhoneNumber = 'phone_number';
    public string $strWebsiteUrl = 'website_url';
    public string $strLastChanged = 'last_changed';
    public string $strLockDate = 'lock_date';
    public string $strSalesAccountCode = 'sales_account_code';
    public string $strVatExemptSalesAccountCode = 'vat_exempt_sales_account_code';
    public string $strIsVatRegistered = 'is_vat_registered';
    public string $strVatPeriod = 'vat_period';
    public string $strFinancialYearEndMonth = 'financial_year_end_month';
}

