<?php
/**
 * ClientModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * ClientModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientModelFields
{
    public string $strId = 'id';
    public string $strName = 'name';
    public string $strLegalName = 'legalName';
    public string $strVatNumber = 'vatNumber';
    public string $strMailAddress = 'mailAddress';
    public string $strStreetAddress = 'streetAddress';
    public string $strEmailAddress = 'emailAddress';
    public string $strPhoneNumber = 'phoneNumber';
    public string $strWebsiteUrl = 'websiteUrl';
    public string $strLastChanged = 'lastChanged';
    public string $strLockDate = 'lockDate';
    public string $strSalesAccountCode = 'salesAccountCode';
    public string $strVatExemptSalesAccountCode = 'vatExemptSalesAccountCode';
    public string $strIsVatRegistered = 'isVatRegistered';
    public string $strVatPeriod = 'vatPeriod';
    public string $strFinancialYearEndMonth = 'FinancialYearEndMonth';
}

