<?php
/**
 * CustomerModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * CustomerModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerModelAttributes
{
    public string $strInvoiceDeliveryType = 'invoice_delivery_type';
    public string $strIsVatFree = 'is_vat_free';
    public string $strDiscountPercent = 'discount_percent';
    public string $strInvoiceEmailAddress = 'invoice_email_address';
    public string $strPaymentTerms = 'payment_terms';
    public string $strUseFactoring = 'use_factoring';
    public string $strSendReminders = 'send_reminders';
    public string $strDoNotAddLatePaymentFees = 'do_not_add_late_payment_fees';
    public string $strDoNotAddLatePaymentInterest = 'do_not_add_late_payment_interest';
    public string $strDeliveryTerm = 'delivery_term';
    public string $strName = 'name';
    public string $strLegalName = 'legal_name';
    public string $strContactPersonId = 'contact_person_id';
    public string $strVatNumber = 'vat_number';
    public string $strWebsiteUrl = 'website_url';
    public string $strSince = 'since';
    public string $strIsPerson = 'is_person';
    public string $strCurrencyCode = 'currency_code';
    public string $strId = 'id';
    public string $strCode = 'code';
    public string $strExternalCode = 'external_code';
    public string $strMailAddress = 'mail_address';
    public string $strStreetAddress = 'street_address';
    public string $strStreetAddresses = 'street_addresses';
    public string $strEmailAddress = 'email_address';
    public string $strPhoneNumber = 'phone_number';
    public string $strIsArchived = 'is_archived';
    public string $strLastChanged = 'last_changed';
    public string $strContactGroups = 'contact_groups';
}

