<?php
/**
 * CustomerBalanceModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * CustomerBalanceModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerBalanceModelFields
{
    public string $strCustomerId = 'customerId';
    public string $strCustomerName = 'customerName';
    public string $strCustomerCode = 'customerCode';
    public string $strCustomerExternalCode = 'customerExternalCode';
    public string $strBalance = 'balance';
}

