<?php
/**
 * CustomerModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * CustomerModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerModelFields
{
    public string $strInvoiceDeliveryType = 'invoiceDeliveryType';
    public string $strIsVatFree = 'isVatFree';
    public string $strDiscountPercent = 'discountPercent';
    public string $strInvoiceEmailAddress = 'invoiceEmailAddress';
    public string $strPaymentTerms = 'paymentTerms';
    public string $strUseFactoring = 'useFactoring';
    public string $strSendReminders = 'sendReminders';
    public string $strDoNotAddLatePaymentFees = 'doNotAddLatePaymentFees';
    public string $strDoNotAddLatePaymentInterest = 'doNotAddLatePaymentInterest';
    public string $strDeliveryTerm = 'deliveryTerm';
    public string $strName = 'name';
    public string $strLegalName = 'legalName';
    public string $strContactPersonId = 'contactPersonId';
    public string $strVatNumber = 'vatNumber';
    public string $strWebsiteUrl = 'websiteUrl';
    public string $strSince = 'since';
    public string $strIsPerson = 'isPerson';
    public string $strCurrencyCode = 'currencyCode';
    public string $strId = 'id';
    public string $strCode = 'code';
    public string $strExternalCode = 'externalCode';
    public string $strMailAddress = 'mailAddress';
    public string $strStreetAddress = 'streetAddress';
    public string $strStreetAddresses = 'streetAddresses';
    public string $strEmailAddress = 'emailAddress';
    public string $strPhoneNumber = 'phoneNumber';
    public string $strIsArchived = 'isArchived';
    public string $strLastChanged = 'lastChanged';
    public string $strContactGroups = 'contactGroups';
}

