<?php
/**
 * CustomerLedgerEntryModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * CustomerLedgerEntryModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerLedgerEntryModelFields
{
    public string $strId = 'id';
    public string $strPostingDate = 'postingDate';
    public string $strDueDate = 'dueDate';
    public string $strVoucherNo = 'voucherNo';
    public string $strCurrencyCode = 'currencyCode';
    public string $strCurrencyAmount = 'currencyAmount';
    public string $strAmount = 'amount';
    public string $strBalance = 'balance';
    public string $strVoucherId = 'voucherId';
    public string $strVoucherDate = 'voucherDate';
    public string $strVoucherType = 'voucherType';
    public string $strMatchId = 'matchId';
    public string $strLastChanged = 'lastChanged';
    public string $strCreatedDate = 'createdDate';
    public string $strCustomer = 'customer';
    public string $strCustomMatchingReference = 'customMatchingReference';
    public string $strExternalImportReference = 'externalImportReference';
    public string $strDocumentNo = 'documentNo';
}

