<?php
/**
 * GeneralLedgerAccountModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * GeneralLedgerAccountModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneralLedgerAccountModelAttributes
{
    public string $strId = 'id';
    public string $strCode = 'code';
    public string $strCreatedFromImportJournalId = 'created_from_import_journal_id';
    public string $strCurrencyCode = 'currency_code';
    public string $strDepartmentCode = 'department_code';
    public string $strIsActive = 'is_active';
    public string $strIsDepartmentRequired = 'is_department_required';
    public string $strIsProjectRequired = 'is_project_required';
    public string $strIsVatCodeLockedAfterPosting = 'is_vat_code_locked_after_posting';
    public string $strLastChanged = 'last_changed';
    public string $strName = 'name';
    public string $strProjectCode = 'project_code';
    public string $strVatCode = 'vat_code';
}

