<?php
/**
 * GeneralLedgerAccountModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * GeneralLedgerAccountModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneralLedgerAccountModelFields
{
    public string $strId = 'id';
    public string $strCode = 'code';
    public string $strCreatedFromImportJournalId = 'createdFromImportJournalId';
    public string $strCurrencyCode = 'currencyCode';
    public string $strDepartmentCode = 'departmentCode';
    public string $strIsActive = 'isActive';
    public string $strIsDepartmentRequired = 'isDepartmentRequired';
    public string $strIsProjectRequired = 'isProjectRequired';
    public string $strIsVatCodeLockedAfterPosting = 'isVatCodeLockedAfterPosting';
    public string $strLastChanged = 'lastChanged';
    public string $strName = 'name';
    public string $strProjectCode = 'projectCode';
    public string $strVatCode = 'vatCode';
}

