<?php
/**
 * GetVoucherDocumentationResponseModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * GetVoucherDocumentationResponseModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GetVoucherDocumentationResponseModelFields
{
    public string $strSuccess = 'success';
    public string $strValidation = 'validation';
    public string $strData = 'data';
}

