<?php
/**
 * IncomingInvoiceVoucherModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * IncomingInvoiceVoucherModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IncomingInvoiceVoucherModelAttributes
{
    public string $strId = 'id';
    public string $strCreatedDate = 'created_date';
    public string $strCurrencyCode = 'currency_code';
    public string $strCurrencyRate = 'currency_rate';
    public string $strSupplierCode = 'supplier_code';
    public string $strDueDate = 'due_date';
    public string $strExternalImportReference = 'external_import_reference';
    public string $strImportedVoucherNo = 'imported_voucher_no';
    public string $strInvoiceNo = 'invoice_no';
    public string $strIsReversed = 'is_reversed';
    public string $strLines = 'lines';
    public string $strVoucherDate = 'voucher_date';
    public string $strVoucherNo = 'voucher_no';
}

