<?php
/**
 * IncomingInvoiceVoucherLineModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * IncomingInvoiceVoucherLineModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IncomingInvoiceVoucherLineModelAttributes
{
    public string $strId = 'id';
    public string $strAccountCode = 'account_code';
    public string $strAmount = 'amount';
    public string $strDescription = 'description';
    public string $strVatCode = 'vat_code';
}

