<?php
/**
 * MailAddressModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * MailAddressModelFields Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MailAddressModelFields
{
    public string $strCity = 'city';
    public string $strZipCode = 'zipCode';
    public string $strAddress1 = 'address1';
    public string $strAddress2 = 'address2';
    public string $strCountryCode = 'countryCode';
    public string $strLastChanged = 'lastChanged';
    public string $strId = 'id';
    public string $strIsPrimary = 'isPrimary';
}

