<?php
/**
 * OutgoingInvoiceVoucherLineModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * OutgoingInvoiceVoucherLineModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutgoingInvoiceVoucherLineModelFields
{
    public string $strId = 'id';
    public string $strAccountCode = 'accountCode';
    public string $strAmount = 'amount';
    public string $strDescription = 'description';
    public string $strVatCode = 'vatCode';
}

