<?php
/**
 * OutgoingInvoiceVoucherModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PowerOfficeGo\Model;

/**
 * OutgoingInvoiceVoucherModelFields Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OutgoingInvoiceVoucherModelFields
{
    public string $strId = 'id';
    public string $strCid = 'cid';
    public string $strCreatedDate = 'createdDate';
    public string $strCurrencyCode = 'currencyCode';
    public string $strCurrencyRate = 'currencyRate';
    public string $strCustomerCode = 'customerCode';
    public string $strCustomMatchingReference = 'customMatchingReference';
    public string $strDeliveryDate = 'deliveryDate';
    public string $strDeliveryTerm = 'deliveryTerm';
    public string $strDueDate = 'dueDate';
    public string $strExternalImportReference = 'externalImportReference';
    public string $strImportedVoucherNo = 'importedVoucherNo';
    public string $strInvoiceNo = 'invoiceNo';
    public string $strDescription = 'description';
    public string $strIsReversed = 'isReversed';
    public string $strLines = 'lines';
    public string $strVoucherDate = 'voucherDate';
    public string $strVoucherNo = 'voucherNo';
}

