<?php
/**
 * GeneralLedgerAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PowerOfficeGo;

/**
 * GeneralLedgerAccountTest Class Doc Comment
 *
 * @category    Class
 * @description GeneralLedgerAccount
 * @package     PowerOfficeGo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GeneralLedgerAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GeneralLedgerAccount"
     */
    public function testGeneralLedgerAccount()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "created_from_import_journal_id"
     */
    public function testPropertyCreatedFromImportJournalId()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "department_code"
     */
    public function testPropertyDepartmentCode()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "is_department_required"
     */
    public function testPropertyIsDepartmentRequired()
    {
    }

    /**
     * Test attribute "is_project_required"
     */
    public function testPropertyIsProjectRequired()
    {
    }

    /**
     * Test attribute "is_vat_code_locked_after_posting"
     */
    public function testPropertyIsVatCodeLockedAfterPosting()
    {
    }

    /**
     * Test attribute "last_changed"
     */
    public function testPropertyLastChanged()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "project_code"
     */
    public function testPropertyProjectCode()
    {
    }

    /**
     * Test attribute "vat_code"
     */
    public function testPropertyVatCode()
    {
    }
}
