<?php
/**
 * IncomingInvoiceVoucherTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PowerOfficeGo;

/**
 * IncomingInvoiceVoucherTest Class Doc Comment
 *
 * @category    Class
 * @description IncomingInvoiceVoucher
 * @package     PowerOfficeGo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IncomingInvoiceVoucherTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IncomingInvoiceVoucher"
     */
    public function testIncomingInvoiceVoucher()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_rate"
     */
    public function testPropertyCurrencyRate()
    {
    }

    /**
     * Test attribute "supplier_code"
     */
    public function testPropertySupplierCode()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "invoice_no"
     */
    public function testPropertyInvoiceNo()
    {
    }

    /**
     * Test attribute "is_reversed"
     */
    public function testPropertyIsReversed()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "voucher_date"
     */
    public function testPropertyVoucherDate()
    {
    }

    /**
     * Test attribute "voucher_no"
     */
    public function testPropertyVoucherNo()
    {
    }
}
