<?php
/**
 * ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PowerOfficeGo;

use \PowerOfficeGo\Configuration;
use \PowerOfficeGo\ApiException;
use \PowerOfficeGo\ObjectSerializer;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdateContactGroup
     *
     * Create or Update Contact Group.
     *
     */
    public function testCreateOrUpdateContactGroup()
    {
    }

    /**
     * Test case for createOrUpdateCustomer
     *
     * Create or Update Customer.
     *
     */
    public function testCreateOrUpdateCustomer()
    {
    }

    /**
     * Test case for createOrUpdateSupplier
     *
     * Create or Update Supplier.
     *
     */
    public function testCreateOrUpdateSupplier()
    {
    }

    /**
     * Test case for getContactGroup
     *
     * Get Contact Group.
     *
     */
    public function testGetContactGroup()
    {
    }

    /**
     * Test case for getCustomer
     *
     * Get Customer.
     *
     */
    public function testGetCustomer()
    {
    }

    /**
     * Test case for getSupplier
     *
     * Get Supplier.
     *
     */
    public function testGetSupplier()
    {
    }

    /**
     * Test case for searchContactGroups
     *
     * Search Contact Groups.
     *
     */
    public function testSearchContactGroups()
    {
    }

    /**
     * Test case for searchCustomers
     *
     * Search Customers.
     *
     */
    public function testSearchCustomers()
    {
    }

    /**
     * Test case for searchSuppliers
     *
     * Search Suppliers.
     *
     */
    public function testSearchSuppliers()
    {
    }
}
