<?php
/**
 * ContactsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * PowerOffice Go API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PowerOfficeGo\Test\Api;

use \PowerOfficeGo\Configuration;
use \PowerOfficeGo\ApiException;
use \PowerOfficeGo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createOrUpdateContactGroup
     *
     * Create or Update Contact Group.
     *
     */
    public function testCreateOrUpdateContactGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrUpdateCustomer
     *
     * Create or Update Customer.
     *
     */
    public function testCreateOrUpdateCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrUpdateSupplier
     *
     * Create or Update Supplier.
     *
     */
    public function testCreateOrUpdateSupplier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactGroup
     *
     * Get Contact Group.
     *
     */
    public function testGetContactGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomer
     *
     * Get Customer.
     *
     */
    public function testGetCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomersBalance
     *
     * Service to query CustomerBalance.
     *
     */
    public function testGetCustomersBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSupplier
     *
     * Get Supplier.
     *
     */
    public function testGetSupplier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchContactGroups
     *
     * Search Contact Groups.
     *
     */
    public function testSearchContactGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCustomers
     *
     * Search Customers.
     *
     */
    public function testSearchCustomers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchSuppliers
     *
     * Search Suppliers.
     *
     */
    public function testSearchSuppliers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
