<?php
/**
 * LedgerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerOffice-Go API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PowerOfficeGo\Test\Api;

use \PowerOfficeGo\Configuration;
use \PowerOfficeGo\ApiException;
use \PowerOfficeGo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LedgerApiTest Class Doc Comment
 *
 * @category Class
 * @package  PowerOfficeGo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LedgerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCustomerLedger
     *
     * Get Customer Ledgers.
     *
     */
    public function testGetCustomerLedger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCustomerLedger
     *
     * Search CustomerLedgers.
     *
     */
    public function testSearchCustomerLedger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchGeneralLedgerAccount
     *
     * Search GeneralLedgerAccount.
     *
     */
    public function testSearchGeneralLedgerAccount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchVatCode
     *
     * Search Vat Code.
     *
     */
    public function testSearchVatCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
